<?php

class Bicycle{

    public $brand;
    public $model;
    public $year;
    public $description = 'Used bicycle';
    // bug in $weight_kg vind het en fix het
    private $weight_kg = 0.0;
    static $wheels = 2;

    public static $instance_count;
    const catergorie = ["Road", "Mountain", "Hybrid", "Cruiser", "City", "BMX"];
    public $catergorie;
    public static $als = true;

    public function name() {
        return $this->brand . " " . $this->model . " (" . $this->year . ")";
    }

    public function weight_lbs() {
        return floatval($this->weight_kg) * 2.2046226218 . " lbs";
    }

    public function set_weight_lbs($value) {
        $this->weight_kg = floatval($value) / 2.2046226218;
    }

    public static function wheel_details(){
        //zat in solution
        $wheel_string = static::$wheels == 1 ? "1 wheel" : static::$wheels ." wheels";
        return "it has " . $wheel_string . ".";
        //return "it has " . $this->wheels . " wheels";
    }

    public function set_weight_kg($kg){
        $this->weight_kg = floatval($kg);
    }

    public function get_weight_kg(){
        return $this->weight_kg . " kg";
    }

    public static function create(){
        $class_name = get_called_class();
        $obj = new $class_name;
        self::$instance_count++;
        return $obj;
        //static::$instance_count++;
        //return static::$instance_count;
    }

    public function setCatergorie($i){
        if($i < 0 ){
            $i = 0;
        }
        if($i > count(self::catergorie)){
            $i = count(self::catergorie) - 1;
        }
        $this->catergorie = self::catergorie[$i];
    }

    public function getCatergorie(){
        return $this->catergorie;
    }
}

class Unicycle extends Bicycle{
    static $wheels = 1;

    //public static $instance_count;

    // zat in sollution
    public function bug_test(){
        //return $this->weight_kg;
    }

    public function name()
    {
        echo parent::name(); // TODO: Change the autogenerated stub
        echo "<br>";
        echo "dit is een een wieler!";
    }

    public static function create()
    {
        if(self::$als){
            return parent::create();
            //echo"parent";
        }
        else{
            static::$instance_count += 100;
            return static::$instance_count;
            //echo"test";

        }
    }
}

$trek = new Bicycle;
$trek->brand = 'Trek';
$trek->model = 'Emonda';
$trek->year = '2017';
$trek->set_weight_kg(1.0);
//$trek->weight_kg = 1.0;

$cd = new Unicycle();
$cd->brand = 'Cannondale';
$cd->model = 'Synapse';
$cd->year = '2016';
$cd->set_weight_kg(8.0);
//$cd->weight_kg = 8.0;

echo $trek->name() . "<br />";


echo $trek->get_weight_kg() . "<br />";
echo $trek->weight_lbs() . "<br />";
// notice that one is property, one is a method

$trek->set_weight_lbs(2);
echo $trek->get_weight_kg() . "<br />";
echo $trek->weight_lbs() . "<br />";

echo $trek->wheel_details() . "<br>";
echo "<br>";
echo $cd->name() . "<br />";
echo $cd->wheel_details() . "<br>";
echo $cd->get_weight_kg(). "<br />";;
echo $cd->weight_lbs() . "<br />";
echo "<hr>";
$trek::create();
echo "fiets " . $trek::$instance_count;
echo "<br>";
$cd::create();
$cd::create();
$cd::create();
echo "een wieler " . $cd::$instance_count;
echo "<hr>";
$trek->setCatergorie(4);
echo $trek->getCatergorie()."<br>";
$trek->setCatergorie(7);
echo $trek->getCatergorie()."<br>";
echo "<hr>";
echo $cd->name();
echo "<br>";
$cd::create();
echo "een wieler " . $cd::$instance_count;
echo"<br>";
$cd::$als = false;
$cd::create();
echo "een wieler "  . $cd::$instance_count;
echo"<br>";


?>
